### ISSUE TITLE
Chinese translation has not been updated for too long

### ISSUE THREAD

**Issue by Genglxy** [TeamCemu/Cemu-Language#70]
It has been almost a year and a half since the end of January 2019. The Chinese translation seems to have never been updated, and many places are untranslated. 
So I translated the latest version on the basis of 1.20.0c myself, but I just noticed that in March this year, a person who was as enthusiastic as me submitted a translation, but you said "There is already a Chinese translator "Rejected him for reasons. 
May I ask when it is possible to merge the translations of current translators? If possible, can we merge our new translation directly?Thanks a lot. #69

**Comment by Fs00** [comment]
In March, a Chinese translator sent me the updated Cemu translation they made (for 1.17.3) on Discord. I asked the translator to make some fixes to their work before pushing it on the repo.
Then PR #49 arrived, and I blocked it because I was waiting for the reply of the Chinese translator on Discord. But this reply has never come.
I will push ASAP the "almost ready" work of the first translator here on the repo, so that you can rebase #69 on top of it (I hope it won't be too painful to do).
@nyanmisaka (author of #49) is welcome to contribute on #69.
